### ISSUE TITLE
文档风格指南：专有名词的样式和链接/代码块周围的空格

### ISSUE THREAD

**Issue by northword** [northword/zotero-guide-zh#211]
链接和一些名词是有专门加一个空格来做区分和强调（文中涉及到插件名的时候，有时候也专门前后加了个空格拆开）。**我觉得核心需求是这一类专有名词需要有一种样式规范来强调一下**，与正文区分开。目前我用的是前后加空格和代码块，加粗的视觉效果区分度不高。

_Originally posted by @wakewon in https://github.com/zotero-chinese/wiki/pull/208#discussion_r1648407286_
            

如果链接前后有空格是文档的风格规范的话，就写到文档风格那章里面吧。

_Originally posted by @jiaojiaodubai in https://github.com/zotero-chinese/wiki/pull/208#discussion_r1648407286_

**Comment by northword** [comment]
CC @jiaojiaodubai @wakewon @zotero-chinese/document-maintainer 

对于专有名词，这种「中式单开引号」如何？这种格式在「少数派」中广泛应用。

![image](https://github.com/zotero-chinese/wiki/assets/44738481/47b26207-216e-4c5a-ad11-a82d21ea3245)

> 引号 - 维基百科：https://zh.wikipedia.org/wiki/%E5%BC%95%E5%8F%B7
> ![image](https://github.com/zotero-chinese/wiki/assets/44738481/cdff0110-3d51-40d2-a80d-3ae2efc3f46d)
> ![image](https://github.com/zotero-chinese/wiki/assets/44738481/3cc40af5-cfed-4a8e-9990-572491540a6e)

**Comment by northword** [comment]
~~这边应该是可以通过工具直接强制把`“”`替换为`「」`~~

No，似乎没有现有的轮子，也许可以自己写脚本夹在 Git Hook 里？或者自己写markdownlint 插件或 prettier 插件。

**Comment by jiaojiaodubai** [comment]
开引号在繁体地区广泛使用，但国家标准倡导的符号是弯引号。排版中使用开引号有一些好处：

1. 视觉区分比较明显，在（电子设备中默认使用的）无衬线字体中不会造成前后引号的混淆。
2. 和西文弯引号不共享 Unicode 码位，不会在排版中造成中文语境下的引号被误当作西文对待。

但是对于简中地区的大多数写作者来说，打出开引号是比较困难的事情，也许需要在项目中配置针对 markdown 的 snippets（类似 <kbd>Ctrl</kbd>+<kbd>B</kbd> 表示加粗之类，也许可以用 <kbd>Ctrl</kbd>+<kbd>Q</kbd>）。

**Comment by northword** [comment]
是的，国标规定的弯引号，不过还好是非强制标准。感觉直引号比弯引号看着舒服一些，并且区分度足够。

最大的痛点就是如何方便快捷地打出这个字符来，snippets 这个方案挺好，很多语法都可以加；

下图截自[少数派写作风格指南](https://manual.sspai.com/rules/style/index.html#_7)：

![image](https://github.com/zotero-chinese/wiki/assets/44738481/4f3e9324-a9e7-4950-9c12-1395f584a48b)

**Comment by northword** [comment]
另外 kbd 这种语法也许也有必要支持，用来显示键盘按键，效果可以参考上图少数派风格指南里的：

```md
<kbd>Ctrl</kbd> + <kbd>C</kbd>
```

<kbd>Ctrl</kbd> + <kbd>C</kbd>

（越整越复杂了 hhh）

**Comment by volatile-static** [comment]
专有名词是不是应该给出解释或者链接呢？我看[有些latex的文档](https://tug.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html)做的很好，应该是自动索引的。简单一些的话像Wikipedia那样hover一个popup也挺好的？

**Comment by northword** [comment]
仅作记录：https://github.com/zhlint-project/zhlint?tab=readme-ov-file#supported-rules 项目似乎可以实现弯角引号转直角引号。

规则：https://github.com/zhlint-project/zhlint/blob/main/src/rules/punctuation-unification.ts

**Comment by northword** [comment]
> 专有名词是不是应该给出解释或者链接呢？我看[有些latex的文档](https://tug.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html)做的很好，应该是自动索引的。简单一些的话像Wikipedia那样hover一个popup也挺好的？

更多的其实是 Zotero 的界面元素（编辑 -> 首选项 这种的），其他诸如“条目”、“字段”这种专有名词似乎也不需要括起来。界面元素这种的话似乎就不需要做 hover popup 了。

其他的专有词例如“Zotero 存储目录”、“同步”这种，可以加超链接到相应的文档？

hover popup 这种，我去研究一下有没有现成的轮子实现。

**Comment by northword** [comment]
仅供记录：

markdownlint 自定义规则 search-and-replace 应该可以完成 弯引号 -> 直角引号 替换：https://www.npmjs.com/package/markdownlint-rule-search-replace

MDN 使用此规则的配置：https://github.com/mdn/content/blob/main/.markdownlint.jsonc#L124

markdownlint custom rule: https://github.com/DavidAnson/markdownlint/blob/main/doc/CustomRules.md
