### ISSUE TITLE
[用户手册] 茉莉花插件：更新 translator

### ISSUE THREAD

**Issue by northword** [northword/zotero-guide-zh#269]
> 这里update translator已经没有了，看讲解教程

_Originally posted by @NunWang in https://github.com/zotero-chinese/wiki/discussions/268#discussioncomment-10380831_

---

![Clip_2024-08-19_17-15-15](https://github.com/user-attachments/assets/23f34a3e-33d6-40b1-9f14-2b11e6ef9187)

这里应链接到 faqs/update-trabnslators 或需要更新描述。

**Comment by Chikit-L** [comment]
> /CC @jiaojiaodubai @Chikit-L 两位觉得应该怎么修改？



### 03. 安装/更新 中文 Translator


安装/更新 中文 Translator教程详见 [一键自动更新Translator](./faqs/update-translators.md/#方法 1：一键自动更新 <Badge text='推荐' />)




我想着是大概改成这个样子？直接导航到Translator更新的教程里面，这样后续也不需要继续维护茉莉花这边的教程了。

**Comment by northword** [comment]
我觉得⭐️

@jiaojiaodubai 因为 cnki 现在下的 pdf 基本上都自带目录了， pdftk 后面会去掉嘛？

**Comment by jiaojiaodubai** [comment]
我不太清楚自动添加书签的具体原理，所以当时重写的时候没写，准备让 @l0o0 帮忙继续完善这一块，既然如此，那便少一事了。我今后对茉莉花的主要维护方向在于对中文 PDF 的文本解析（有望直接读出英文信息），添加查找消息的接口（其实重写版现在已经能以实现接口的方式直接调用 Translator 了）

**Comment by northword** [comment]
#273
