### ISSUE TITLE
[功能建议]求实现zotero与onenote联动

### ISSUE THREAD

**Issue by muyuxiaoxiao96** [northword/zotero-guide-zh#56]
目前找了很久都没有和OneNote联动的，，OneNote有一个功能是复制指向页面的链接，但是这个链接不止是能够网页访问，也可以截取链接的后半段（onenote:https://开始）实现本地从其他应用跳转到onenote，如果能借此实现zotero的跳转就很棒了；

希望功能：1.在zotero中可以为参考文献创建onenote页面（预先配置好具体的OneNote分区），自动创建或者根据用户选择创建；然后实现zotero跳转到OneNote；
2.Onenote中跳转回zotero

**Comment by chasonly** [comment]
同意同意

**Comment by Guochaoli** [comment]
2025年了，请问大家实现了吗？
