### ISSUE TITLE
zotero文献阅读可以同时打开两篇不同的文献对比阅读吗

### ISSUE THREAD

**Issue by LHT-Liu** [northword/zotero-guide-zh#67]
zotero文献阅读可以同时打开两篇不同的文献对比阅读吗，我知道同一篇文献的横向竖向分屏阅读，不同文献可以吗

**Comment by northword** [comment]
使用单独窗口打开文献

![image](https://github.com/zotero-chinese/wiki/assets/44738481/4035df99-210f-4a80-b89b-8d3583ad12ae)


![image](https://github.com/zotero-chinese/wiki/assets/44738481/85a963ef-a0f5-498e-a70a-31159b0a8040)

**Comment by LHT-Liu** [comment]
请问这个是7特有的吗，我在6里面好像没找到这个

**Comment by northword** [comment]
记不清了，没有的话就是7特有的吧

**Comment by Jerome-Cong** [comment]
6里面已经打开的pdf可以通过右键移动标签到新窗口来多开

**Comment by LHT-Liu** [comment]
> 6里面已经打开的pdf可以通过右键移动标签到新窗口来多开

好的好的，感谢您
